trigger:
- none

pool:
  vmImage: windows-latest

steps:
- script: packer init .
#- task: packer build 'azureimage.pkr.hcl'
    
- task: Bash@3
  displayName: 'Packer build'
  inputs:
    targetType: 'inline'
    script: |
      $clientId = ${env:ARM_CLIENT_ID}
      $clientSecret = ${env:ARM_CLIENT_SECRET}
    
      packer build azureimage.pkr.hcl
