trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: packer-image-build-variables
steps:
- script: packer init .


- task: PackerBuild@0
  inputs:
    templateType: 'custom'
    customTemplateLocation: azureimage.pkr.json
    packerVersion: 1.11.2
  