trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: packer-image-build-variables
steps:
- script: packer init .


- task: PackerBuild@1
  inputs:
    templateType: 'custom'
    customTemplateLocation: azureimage.json
    packerVersion: 1.11.2
  