trigger:
- none

pool:
  vmImage: ubuntu-latest

# variables:
# - group: packer-image-build-variables

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'akserviceconnection1'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
      packer init .
      packer build azureimage.pkr.hcl

  env:
   
    PKR_VAR_gallery_image_name: $(GALLERY_IMAGE_NAME)
    PKR_VAR_resource_group_name: $(RESOURCE_GROUP_NAME)
    PKR_VAR_storageAccountKey: $(STORAGE_ACCOUNT_KEY)
    PKR_VAR_winrm_password: $(WINRM_PASSWORD)