trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: packer init .
#- task: packer build 'azureimage.pkr.hcl'
    
- task: Bash@3
  displayName: 'Packer build'
  inputs:
    targetType: 'inline'
    script: |
      $clientId = $(ARM_CLIENT_ID)
      $clientSecret = $(ARM_CLIENT_SECRET)
    
      packer build azureimage.pkr.hcl


 
    




