trigger:
- none

pool:
  vmImage: ubuntu-latest

env: 
  PKR_VAR_subscription_id: $(ARM_SUBSCRIPTION_ID)
  PKR_VAR_tenant_id: $(ARM_TENANT_ID)
  PKR_VAR_client_id: $(ARM_CLIENT_ID)
  PKR_VAR_client_secret: $(ARM_CLIENT_SECRET)
  PKR_VAR_primary_location: $(GALLERY_IMAGE_NAME)
  PKR_VAR_image_name: $(RESOURCE_GROUP_NAME)
  PKR_VAR_image_version: $(STORAGE_ACCOUNT_KEY)
  PKR_VAR_gallery_resource_group: $WINRM_PASSWORD)

# variables:
# - group: packer-image-build-variables

steps:
- script: |
    echo "Installing Packer..."
    sudo apt-get update -y
    sudo apt-get install -y packer

    echo "Packer version:"
    packer version

    echo "running packer init..."
    packer init .
    packer build azureimage.pkr.hcl
  displayName: 'Run Packer'