trigger:
- none

pool:
  vmImage: ubuntu-latest

# variables:
# - group: packer-image-build-variables

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'akserviceconnection1'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login --service-principal -u 13e26b33-e672-4ad9-a3ec-ec9950b96a0f -p Qgy8Q~B92ZtUovFHPF2kieS_a1RnD0DsEptbKaLp --tenant f6b9b1fa-10dd-4c5b-8b1b-404934b17313
      packer init .
      packer build azureimage.pkr.hcl

  env:
   
    PKR_VAR_gallery_image_name: $(GALLERY_IMAGE_NAME)
    PKR_VAR_resource_group_name: $(RESOURCE_GROUP_NAME)
    PKR_VAR_storageAccountKey: $(STORAGE_ACCOUNT_KEY)
    PKR_VAR_winrm_password: $(WINRM_PASSWORD)