trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: packer init
- script: packer build    
- task: riezebosch.Packer.Packer.Packer@1
  displayName: 'Packer build'
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription(761cc7e6-a477-494a-99ef-a5d6aa0fde41)'
    templatePath: azureimage.pkr.hcl
