trigger:
- none

pool:
  vmImage: windows-latest

steps:
- script: packer init .
#- task: packer build 'azureimage.pkr.hcl'

- script: 'curl -H "Metadata: true" http://169.254.169.254/metadata/identity/oauth2/token'
    
- task: Bash@3
  displayName: 'Packer build'
  inputs:
    targetType: 'inline'
    script: |
      $clientId = ${env:ARM_CLIENT_ID}
      $clientSecret = ${env:ARM_CLIENT_SECRET}
    
      packer build azureimage.pkr.hcl

